language: node_js
sudo: false

node_js:
  - "10"
  - "12"
  - "14"

git:
  depth: false

env:
  - STAN_VERSION=v0.21.1

before_script:
  - wget "https://github.com/nats-io/nats-streaming-server/releases/download/$STAN_VERSION/nats-streaming-server-$STAN_VERSION-linux-amd64.zip" -O tmp.zip
  - unzip tmp.zip
  - mv "nats-streaming-server-$STAN_VERSION-linux-amd64" nats-streaming-server
  - mkdir nats-streaming-server/logs


script:
  - npm test

after_success:
  - if [[ "$TRAVIS_NODE_VERSION" == 13 ]]; then npm run coveralls; fi

after_failure:
  - cat nats-streaming-server/logs/*.log
